### ISSUE TITLE
"ImportError: cannot import name 'ccfDisableAutoLoading' from 'vapoursynth'" on Vapoursynth R68

### ISSUE THREAD

**Issue by shssoichiro** [Jaded-Encoding-Thaumaturgy/vs-tools#107]
It seems this is traced back to this import line: https://github.com/Jaded-Encoding-Thaumaturgy/vs-tools/blob/809df6643f7d6bdc0f224805446b22bc885fdf10/vstools/utils/vs_proxy.py#L17

R68 seems to no longer be exporting the following items, which is causing this issue:

`ccfDisableAutoLoading`, `ccfDisableLibraryUnloading`, `ccfEnableGraphInspection`, `fmFrameState`, `fmParallel`, `fmParallelRequests`, `fmUnordered`

**Comment by Vodes** [comment]
Known issue. https://github.com/Jaded-Encoding-Thaumaturgy/vs-jet/issues/10

It is currently very much recommended to stay on r66.

**Comment by marillat** [comment]
It's really annoying when 68 is already installed and you are using a Debian repository  DMO

**Comment by LightArrowsEXE** [comment]
Fixed in #108

**Comment by marillat** [comment]
Thanks.
