### ISSUE TITLE
File type parsing improve heuristics

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-tools#112]
With certain files, the wrong filetype appears to be getting parsed.

For example, [this](https://lightarrowsexe.zion.usbx.me/filebrowser/api/public/dl/yQU6ODIh/share/public/Other/issues/00002.m2ts) m2ts file prases as an AC3 file. 

```py
ParsedFile(path=WindowsPath('C:/Users/light/Encoding/temp/maria/00002.m2ts'), ext='.ac3', encoding=None, file_type=<FileType.AUDIO: 'audio'>, mime='application/octet-stream')
```

ffprobe's results:

```
Input #0, mpegts, from '00002.m2ts':
  Duration: 00:25:27.87, start: 5614.566667, bitrate: 42425 kb/s
  Program 1
  Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn
  Stream #0:1[0x1100]: Audio: pcm_bluray (HDMV / 0x564D4448), 48000 Hz, stereo, s16, 1536 kb/s
  Stream #0:2[0x1101]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 448 kb/s
```

The first couple bytes

```py
file_bytes=b'\x0bw\\\xccG@\x00\x10\x00\x00\xb0\x11\x00\x00\xc1\x00\x00\x00'
```

This file gets parsed correctly upon any form of remuxing, even when trying to generate a test clip using the following command:

```shell
ffmpeg -to 0:03.00 -i "00002.m2ts" -c copy test.m2ts
```

Having additional heuristics to determine a file type would be appreciated, but I'm not sure how much can be done here.
One kind of hacky solution I can think of for `vssource.source` is to check if a video is parsed as anything but VIDEO/IMAGE, and then try simpler heuristics and see if those return a video or image.

**Comment by Setsugennoao** [comment]
Can just force ffprobe
