### ISSUE TITLE
scale_value does not scale int to float correctly

### ISSUE THREAD

**Issue by Vodes** [Jaded-Encoding-Thaumaturgy/vs-tools#114]
"(or possibly, does not scale limited to full entirely, but i have not checked int limited->full)"

![image](https://github.com/user-attachments/assets/ed9b52eb-406f-40aa-9db7-953fee5d7de2)

**Comment by Setsugennoao** [comment]
It does, just do scale_offset=True

**Comment by Setsugennoao** [comment]
Updated the behaviour such that if the ranges mismatch, by default it will be True
