### ISSUE TITLE
invert_ranges: Does not return proper ranges

### ISSUE THREAD

**Issue by LightArrowsEXE** [Jaded-Encoding-Thaumaturgy/vs-tools#90]
This is really an issue with `replace_ranges`, but I could trace it as far back as invert_ranges I believe.
From what I can gather, it does not properly return an inversion of the ranges, so `replace_ranges`' `a_trims` becomes a single clip the length of the original clip as opposed to the two necessary. The `b_trims` get appended at the end instead of sandwiched between them as it should.

```py
    out = replace_ranges(clip, clip.std.BlankClip(keep=True), [(1000, 9000)])
    print("og clip", clip.num_frames)
    print("out clip", out.num_frames)
```

```terminal
og clip 34765
out clip 42766
```

Clips passed to `replace_ranges`:

```
VideoNode
        Format: YUV420P16
        Width: 1920
        Height: 1080
        Num Frames: 34765
        FPS: 24000/1001

 VideoNode
        Format: YUV420P16
        Width: 1920
        Height: 1080
        Num Frames: 34765
        FPS: 24000/1001
```

a and b_ranges
```
[(0, 34764)]
[(1000, 9000)]
```

**Comment by Setsugennoao** [comment]
Fixed here https://github.com/Setsugennoao/stgpytools/commit/05bcd73ba393fb76c9b38b67fe2a6ff5e1f3b3d3
